CREATE TABLE PLAYER(
    _ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PLAYERNUM VARCHAR(2) NOT NULL,
    PLAYERNAME VARCHAR(25) NOT NULL,
    TEAM VARCHAR(24),
    PLAYERPOS VARCHAR(16),
    TEAMID VARCHAR(2)
);

CREATE TABLE TEAM(
    _ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TEAMID INT,
    TEAMNAME VARCHAR(24) NOT NULL,
    BANNER VARCHAR(200) NOT NULL
);

ALTER TABLE PLAYER ADD FOREIGN KEY (TEAMID) REFERENCES TEAM(_ID);